# fly.toml file generated for wispy-bird-8709 on 2021-04-16T14:03:50-04:00

app = "wispy-bird-8709"

kill_signal = "SIGINT"
kill_timeout = 5

[env]

[[services]]
  http_checks = []
  internal_port = 443
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
